name: Latest Music
on: 
    schedule:
        - cron: '6 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with Updated YT Playlist
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "10"
                feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLuWs5sMPaxNj2aS1MtLMgcUsNuldIeynG"
