name: Latest Music
on: 
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with Updated YT Playlist
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "15"
                feed_list: https://youtube.com/playlist?list=PLuWs5sMPaxNiFdKiAOtP6HYxoYWt8NAC9
